name: MyLibrary Local
values:
  - key: baseUrl
    enabled: true
    value: 'http://localhost:8080'
  - key: adminToken
    enabled: true
    value: ''
  - key: joaoToken
    enabled: true
    value: ''
  - key: mariaToken
    enabled: true
    value: ''
  - key: anaToken
    enabled: true
    value: ''
  - key: clubId
    enabled: true
    value: ''
  - key: b1Id
    enabled: true
    value: ''
  - key: b2Id
    enabled: true
    value: ''
  - key: b3Id
    enabled: true
    value: ''
  - key: inv1Id
    enabled: true
    value: ''
  - key: inv2Id
    enabled: true
    value: ''
  - key: inv3Id
    enabled: true
    value: ''
  - key: deviceId
    enabled: true
    value: book-club-tester-001
  - key: deviceName
    enabled: true
    value: Book Club Flow Tester
